name: grpc_cronet
description: Flutter plugin that provides Cronet-based grpc client implementation.
version: 0.0.7
repository: https://github.com/dart-lang/grpc_cronet

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: ^2.11.0

dependencies:
  flutter:
    sdk: flutter
  ffi: '>=1.2.1 <2.0.0'
  grpc: ^3.0.2
  http2: ^2.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^5.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true

false_secrets:
 - /example/helloworld/lib/assets/data/private.key
 - /example/route_guide/lib/assets/data/private.key
